include ../make.def

VERSION=0.8
SRC=io-watchdog-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/io-watchdog/$(TAR)"

include ../make.workbench
