include ../make.def

VERSION=2.4.1
SRC=scrub-$(VERSION)
TAR=$(SRC).tar.gz
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/diskscrub/$(TAR)"

include ../make.workbench
