#!/usr/bin/env bash
set -euo pipefail
################################################################################
# Name:       deploy
# File:       deploy
# Purpose:    call make in src to build/install as rpm or a directory
# Bug Reports: cap5-devel_AT_lists_DOT_sf_DOT_net
#
# Copyright:
# © Copyright 2012 Hewlett-Packard Development Company, L.P
#
# License: GPL v2
################################################################################

if [[ -f /usr/libexec/cap5/sh/cfunc ]]; then
    # shellcheck source=libexec/sh/cfunc
    source /usr/libexec/cap5/sh/cfunc
elif [[ -n "${CAPHOME:-}" && -f "${CAPHOME}/libexec/sh/cfunc" ]]; then
    # shellcheck source=libexec/sh/cfunc
    source "${CAPHOME}/libexec/sh/cfunc"
else
    echo "Missing cfunc library" >&2
    exit 1
fi

usage() {
    cinfo "$0 --tool TOOLNAME --rpm --clean|--distclean"
    cinfo "$0 --tool TOOLNAME --prefix PREFIXDIRECTORY  --clean|--distclean"
    exit 1
}

parsecli "$@"

check_validvar TOOL "${TOOL}"

if [[ "${RPM}" -eq 1 ]]; then
    [[ "${DEBUG}" -gt 0 ]] && cdebug "make_tool ${TOOL} => RPM"
    make_tool "${TOOL}"
else
    check_validvar PREFIX "${PREFIX}"
    [[ "${DEBUG}" -gt 0 ]] && cdebug "make_tool ${TOOL} => ${PREFIX}"
    make_tool "${TOOL}" "${PREFIX}"
fi


: <<=cut

=pod

=head1 deploy

deploy - deploy cap src programs as rpms/debs or in a specific directory for use

=head1 SYNOPSIS

  $ deploy --tool TOOLNAME --rpm
  $ deploy --tool TOOLNAME --prefix PREFIXDIRECTORY

=head1 DESCRIPTION

More detailed description of your program.  Include CLI, Options, Variable Names, Exported Subroutines, Internal Subroutines.

=head1 SEE ALSO

Local documentation should be accessible in
  /usr/share/doc/cap5/

Submit any questions/requests/gripes to the CAP-users mailing list:
        cap5-users_AT_lists_DOT_sf_DOT_net

Updated software and documentation may be found at the CAP web site:
        http://www.capforge.org

=head1 COPYRIGHT AND LICENSE

© Copyright 2012 Hewlett-Packard Development Company, L.P

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

=cut
