include ../make.def

BASEVERSION=1.20
VERSION=1.20-1
SRC=genders-$(BASEVERSION)
TAR=$(SRC).tar.gz
URL="https://sourceforge.net/projects/genders/files/genders/$(VERSION)/$(TAR)"

include ../make.workbench
