include ../make.def

VERSION=3.2.8a
SRC=environment-modules-$(VERSION)
SRPM=$(SRC)-2.rf.src.rpm
TAR=$(SRPM)
#TAR=$(SRC).src.tar.gz
#URL="http://sourceforge.net/projects/collectl/files/collectl/$(SRC)/$(SRPM)"
URL="http://pkgs.repoforge.org/environment-modules/$(TAR)"

#
# sf source pull, if we decide to install it locally instead, need to use this below
#
#VERSION=3.2.9
#SUBVERSION=c
#RPMPKGNAME=environment-modules
#SFDIR=modules-$(VERSION)
#SRC=modules-$(VERSION)$(SUBVERSION)
#TAR=$(SRC).tar.gz
#URL="http://sourceforge.net/projects/modules/files/Modules/$(SFDIR)/$(TAR)"

include ../make.workbench

