include ../make.def

VERSION=0.19
SRC=sqlog-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/sqlog/$(TAR)"

include ../make.workbench
