include ../make.def

VERSION=0.2.7
SRC=conman-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/conman/$(TAR)"

include ../make.workbench
