include ../make.def

VERSION=3.6.3
SRC=collectl-$(VERSION)
#TAR=$(SRC).src.tar.gz
SRPM=$(SRC)-2.src.rpm
TAR=$(SRPM)
URL="http://sourceforge.net/projects/collectl/files/collectl/$(SRC)/$(SRPM)"

include ../make.workbench
