include ../make.def

VERSION=3.2.0
SRC=collectl-utils-$(VERSION)
#TAR=$(SRC).src.tar.gz
SRPM=$(SRC)-1.src.rpm
TAR=$(SRPM)
URL="http://sourceforge.net/projects/collectl-utils/files/$(SRC)/$(SRPM)"

include ../make.workbench
