include ../make.def

VERSION=3.14
SRC=nfsroot-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/nfsroot/$(TAR)"

include ../make.workbench
