include ../make.def

VERSION=2.3.12
SRC=powerman-$(VERSION)
TAR=$(SRC).tar.gz
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/powerman/$(TAR)"

include ../make.workbench
