include ../make.def

BASEVERSION=1.19
VERSION=1.19-1
SRC=gendersllnl-$(BASEVERSION)
TAR=$(SRC).tar.gz
URL="https://sourceforge.net/projects/genders/files/gendersllnl/$(VERSION)/$(TAR)"

include ../make.workbench
