include ../make.def

VERSION=0.5.10
SRC=munge-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/munge/$(TAR)"

include ../make.workbench
