#!/bin/bash
set -euo pipefail
################################################################################
# Name:       cfunc
# File:       cfunc
# Purpose:    library of bash functions for cap5
# Bug Reports: cap5-devel_AT_lists_DOT_sf_DOT_net
#
# Copyright:
# © Copyright 2012 Hewlett-Packard Development Company, L.P
#
# License: GPL v2
################################################################################

TOOL=''
PREFIX=''
RPM=0
CLEAN=0
DISTCLEAN=0
DEBUG=0

cprint() {
    local tag="${1:?tag required}"
    shift
    local red='' grn='' ylw='' blu='' cyn='' bld='' rst=''
    if [[ -t 1 ]] && command -v tput &>/dev/null; then
        red=$(tput setaf 1 2>/dev/null || true)
        grn=$(tput setaf 2 2>/dev/null || true)
        ylw=$(tput setaf 3 2>/dev/null || true)
        blu=$(tput setaf 4 2>/dev/null || true)
        cyn=$(tput setaf 6 2>/dev/null || true)
        bld=$(tput bold   2>/dev/null || true)
        rst=$(tput sgr0   2>/dev/null || true)
    fi
    case "${tag}" in
        info)  printf '%s%s%s\n' "${bld}${blu}" "$*" "${rst}" ;;
        pass)  printf '%s%s%s\n' "${bld}${grn}" "$*" "${rst}" ;;
        debug) printf '%s%s%s\n' "${bld}${cyn}" "$*" "${rst}" ;;
        warn)  printf '%s%s%s\n' "${bld}${ylw}" "$*" "${rst}" ;;
        error) printf '%s%s%s\n' "${bld}${red}" "$*" "${rst}" >&2 ;;
        *)     printf '%s%s%s\n' "${bld}"        "$*" "${rst}" ;;
    esac
}

cinfo()  { cprint info  "$@"; }
cdebug() { cprint debug "$@"; }
cpass()  { cprint pass  "$@"; }
cwarn()  { cprint warn  "$@"; }
cerror() { cprint error "$@"; }

parsecli() {
    TOOL=''
    PREFIX=''
    RPM=0
    CLEAN=0
    DISTCLEAN=0
    DEBUG=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --tool)
                # shellcheck disable=SC2034
                TOOL="${2:?--tool requires a value}"
                shift 2
                ;;
            --prefix)
                PREFIX="${2:?--prefix requires a value}"
                shift 2
                ;;
            --rpm)       RPM=1;       shift ;;
            --clean)     CLEAN=1;     shift ;;
            --distclean) DISTCLEAN=1; shift ;;
            --debug|--verbose) DEBUG=1; shift ;;
            --help|--usage) usage ;;
            --) shift; break ;;
            -*) cerror "Unknown option: $1"; usage ;;
            *)  break ;;
        esac
    done

    if [[ "${DEBUG}" -gt 1 ]]; then
        cdebug "Remaining args:"
        for arg; do echo "--> \`${arg}\`"; done
    fi
}

check_validvar() {
    if [[ $# -lt 2 ]]; then
        cerror "Usage: check_validvar VARIABLE_NAME VARIABLE_VALUE"
        return 1
    fi
    if [[ -z "${2}" ]]; then
        cerror "Undefined variable: ${1}"
        return 1
    fi
}

pkg_search() {
    if [[ $# -lt 2 ]]; then
        cerror "Usage: pkg_search yum|rpm|apt|apt-cache|deb packagename"
        return 1
    fi
    if [[ "$1" == "yum" || "$1" == "rpm" ]]; then
        yum search "$2" | grep "^${2}"
    elif [[ "$1" == "apt-cache" || "$1" == "apt" || "$1" == "deb" ]]; then
        apt-cache search "$2" | grep "^${2}"
    else
        cerror "$1 is not a known search method"
        return 1
    fi
}

make_tool() {
    if [[ $# -lt 1 ]]; then
        cerror "Usage: make_tool TOOL [PREFIXOPTION]"
        exit 1
    fi
    local tool="$1"
    local maketooldir
    shift

    if [[ -d "/usr/src/cap5/${tool}" ]]; then
        maketooldir="/usr/src/cap5/${tool}"
    else
        if [[ -z "${CAPHOME:-}" || ! -d "${CAPHOME}/src/${tool}" ]]; then
            cerror "Missing make directory src for ${tool}"
            exit 1
        fi
        maketooldir="${CAPHOME}/src/${tool}"
    fi

    if [[ "${RPM}" -eq 1 && -n "${PREFIX}" ]]; then
        cinfo "UNDER DEVELOPMENT: make_tool called with a prefix for rpm"
        exit 1
    fi
    [[ "${CLEAN}" -eq 1 && "${DISTCLEAN}" -eq 0 ]] && make -C "${maketooldir}" clean
    [[ "${DISTCLEAN}" -eq 1 ]] && make -C "${maketooldir}" distclean
    if [[ "${RPM}" -eq 1 ]]; then
        make -C "${maketooldir}" rpm
        make -C "${maketooldir}" rpmstatus
        make -C "${maketooldir}" rpminstall
    else
        PREFIX="${PREFIX}" make -C "${maketooldir}" install
    fi
}

: <<=cut

=pod

=head1 cfunc

cfunc - library of bash functions for cap5

=head1 SYNOPSIS

=head1 DESCRIPTION

More detailed description of your program.  Include CLI, Options, Variable Names, Exported Subroutines, Internal Subroutines.

=head1 SEE ALSO

Local documentation should be accessible in
  /usr/share/doc/cap5/

Submit any questions/requests/gripes to the CAP-users mailing list:
        cap5-users_AT_lists_DOT_sf_DOT_net

Updated software and documentation may be found at the CAP web site:
        http://www.capforge.org

=head1 COPYRIGHT AND LICENSE

© Copyright 2012 Hewlett-Packard Development Company, L.P

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

=cut
