#!/bin/bash
################################################################################
# Name:		cfunc
# File:		cfunc
# Purpose:	call make in src to build/install as rpm or a directory
# Bug Reports:	cap4-devel_AT_lists_DOT_sf_DOT_net
#
# Last Modified:
# $Id: cap-program-template 1349 2009-01-28 16:09:23Z jatencio $
#
# Copyright:
# © Copyright 2012 Hewlett-Packard Development Company, L.P
#
# License: GPL v2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
################################################################################

RPM=0
CLEAN=0
DISTCLEAN=0
DEBUG=0
VERBOSE=0

cprint() {
        local tag=$1
        check_validvar tag $tag
        shift

	# Text color variables
	txtred='\e[0;31m'       # red
	txtgrn='\e[0;32m'       # green
	txtylw='\e[0;33m'       # yellow
	txtblu='\e[0;34m'       # blue
	txtpur='\e[0;35m'       # purple
	txtcyn='\e[0;36m'       # cyan
	txtwht='\e[0;37m'       # white
	bldred='\e[1;31m'       # red    - Bold
	bldgrn='\e[1;32m'       # green
	bldylw='\e[1;33m'       # yellow
	bldblu='\e[1;34m'       # blue
	bldpur='\e[1;35m'       # purple
	bldcyn='\e[1;36m'       # cyan
	bldwht='\e[1;37m'       # white
	txtund=$(tput sgr 0 1)  # Underline
	txtbld=$(tput bold)     # Bold
	txtrst='\e[0m'          # Text reset

	# Feedback indicators
	info=${bldwht}*${txtrst}
	pass=${bldblu}*${txtrst}
	warn=${bldred}!${txtrst}

	# Indicator usage
	case "$tag" in
		"info") echo -e "${bldblu}$@";;
		"pass") echo -e "${bldgrn}$@";;
		"debug") echo -e "${bldcyn}$@";;
		"warn") echo -e "${bldylw}$@";;
		"error") echo -e "${bldred}$@";;
		*) echo -e "${bldpur}$@";;
	esac
	tput sgr0
}

cinfo() { cprint info "$@"; }
cdebug() { cprint debug "$@"; }
cpass() { cprint pass "$@"; }
cwarn() { cprint warn "$@"; }
cerror() { cprint error "$@"; }

parsecli() {
        ARG="$@"
        # Note that we use `"$@"' to let each command-line parameter expand to a 
        # separate word. The quotes around `$@' are essential!
        # We need TEMP as the `eval set --' would nuke the return value of getopt.
        TEMP=`getopt -o hc:: -l tool:,prefix:,rpm,clean,distclean,help,usage,debug \
        -n 'ERROR' -- "$@"`
        if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
        # Note the quotes around `$TEMP': they are essential!
        eval set -- "$TEMP"

	while true ; do
		case "$1" in
			--tool) TOOL=$2; shift 2 ;;
			--prefix) PREFIX=$2; shift 2 ;;
			--rpm) RPM=1; shift ;;
			--clean) CLEAN=1; shift ;;
			--distclean) DISTCLEAN=1; shift ;;
			--help|--usage) usage ;;
			--debug) DEBUG=1; shift ;;
			--verbose) DEBUG=1; shift ;;
			--) shift ; break ;;
			*) cerror "Internal error!" ; exit 1 ;;
		esac
	done
        if [ $DEBUG -gt 1 ] ; then
                cdebug "Remaining args:"
                for arg do echo '--> '"\`$arg\`" ; done
        fi
}

check_validvar() {
	[ $# -lt 1 ] && cerror "VARIABLE_NAME VARIABLE_VALUE" && usage 
	[ "x${2}" = "x" ] && cerror "Undefined VARIABLE ${1}" && usage 
}

pkg_search() {
	[ $# -lt 2 ] && cerror "yum|rpm|apt|apt-cache|deb packagename" && usage 
        if [ $1 = "yum" -o $1 = "rpm" ]; then 
                yum search $2 | grep ^$2
        elif [ $1 = "apt-cache" -o $1 = "apt" -o $1 = "deb" ]; then 
                apt-cache search $2 | grep ^$2
	else
		cerror "$1 is not a known method to search for $1"
        fi
}

make_tool() {
	[ $# -lt 1 ] && cerror "make_tool TOOL PREFIXOPTION" && exit 1
	local tool=$1
	shift

	if [ -d /usr/src/cap4/${tool} ]; then
		maketooldir=/usr/src/cap4/${tool}
	else
		# CAPHOME defined and if defined is there a tool there library
		[ "x${CAPHOME}" = "x" ] || 
		 [ "x${CAPHOME}" != "x" -a ! -d ${CAPHOME}/src/${tool} ] && 
		 cerror "Missing make directory src for $tool" && exit 1

		maketooldir=${CAPHOME}/src/${tool}
	fi

	if [ $RPM -eq 1 -a "x${PREFIX}" != "x" ]; then
		cinfo "UNDER DEVELOPMENT: make_tool called with a prefix for rpm"
		exit 1
	fi
	[ $CLEAN -eq 1 -a $DISTCLEAN -eq 0 ] && make -C $maketooldir clean
	[ $DISTCLEAN -eq 1 ] && make -C $maketooldir distclean
	if [ $RPM -eq 1 ]; then
		make -C $maketooldir rpm
		make -C $maketooldir rpmstatus
		make -C $maketooldir rpminstall
	else
		PREFIX=$PREFIX make -C $maketooldir install
	fi
}

: <<=cut

=pod

=head1 cfunc

cfunc - library of bash functions for cap4

=head1 SYNOPSIS

=head1 DESCRIPTION

More detailed description of your program.  Include CLI, Options, Variable Names, Exported Subroutines, Internal Subroutines.

=head1 SEE ALSO

Local documentation should be accessible in 
  /usr/share/doc/cap4/ 

Submit any questions/requests/gripes to the CAP-users mailing list:
        cap4-users_AT_lists_DOT_sf_DOT_net

Updated software and documentation may be found at the CAP web site:
        http://www.capforge.org

=head1 COPYRIGHT AND LICENSE

© Copyright 2012 Hewlett-Packard Development Company, L.P

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 

=cut
