include ../make.def

VERSION=0.13
SRC=slurm-spank-plugins-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/slurm-spank-plugins/$(TAR)"

include ../make.workbench
