include ../make.def

VERSION=1.2.3
SRC=nodediag-$(VERSION)
TAR=$(SRC).tar.bz2
URL="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/nodediag/$(TAR)"

include ../make.workbench
